### ISSUE TITLE
error: no such subcommand: `add`

### ISSUE THREAD

**Issue by ghost** [rustasync/memdb#8]
**Choose one:** is this a 🐛 bug report

## Current Behavior

The [readme](https://github.com/rustasync/memdb#installation) says:
```
Installation
$ cargo add memdb
```

but cargo says:
```
error: no such subcommand: `add`

	Did you mean `doc`?
```

$ cargo -vV
cargo 1.39.0-nightly (ab6fa8908 2019-09-25)
release: 1.39.0
commit-hash: ab6fa8908c9b6c8f7e2249231c395eebfbc49891
commit-date: 2019-09-25

## Possible Solution

`cargo install memdb` ?
```
error: specified package `memdb v1.0.0` has no binaries
```
nope, guess that's not it.
Manually adding it to `[dependencies]` in `Cargo.toml` ?

## Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Package          | ?
| Runtime          | ?
| Package Manager  | pacman
| Operating System | Arch Linux 64bit

**Comment by yoshuawuyts** [comment]
`cargo add` is part of [`cargo-edit`](https://github.com/async-rs/async-std/pull/269/checks?check_run_id=243557011); I kind of assumed this would've been merged with cargo in the last 2 years, but we're still not there.
